### ISSUE TITLE
Error when upgrading fro 2.2.3 to 2.3.1 "couldn't find file 'recurring_select'

### ISSUE THREAD

**Issue by robp2175** [concerto-addons/concerto_template_scheduling#16]
This is the same issue as here https://github.com/concerto-addons/concerto_content_scheduling/issues/22, but I never actually solved the issue. Would like to finally solve this to perform the upgrade. Tried completely removing the plugin with gem uninstall, but that did not work, also tried delete it from the Web UI. Any help is greatly appreciated.

```
concerto@concerto:/root$ sudo apt-get upgrade -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  apache2 apache2-bin apache2-data apache2-mpm-worker base-passwd bsdutils dbus gir1.2-freedesktop gir1.2-glib-2.0 icedtea-7-jre-jamvm imagemagick isc-dhcp-client
  isc-dhcp-common libapache2-mod-passenger libatk1.0-0 libatk1.0-data libgl1-mesa-dri libglib2.0-0 libglib2.0-bin libglib2.0-dev libgstreamer1.0-0 libgtk2.0-0 libgtk2.0-bin
  liblept4 libmagickcore-dev libmagickwand-dev libpulse0 libreoffice libreoffice-base libreoffice-base-core libreoffice-base-drivers libreoffice-calc libreoffice-core
  libreoffice-draw libreoffice-impress libreoffice-math libreoffice-writer mount openjdk-7-jre openjdk-7-jre-headless python3-uno ruby-passenger ruby-rmagick ufraw-batch
  util-linux util-linux-locales wget
0 upgraded, 0 newly installed, 0 to remove and 47 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up concerto-full (2.3.1) ...
dbconfig-common: writing config to /etc/dbconfig-common/concerto-full.conf
dbconfig-common: flushing administrative password
Successfully installed rake-10.4.2
Successfully installed bundler-1.10.6
2 gems installed
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.8.0
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.1.12
Using builder 3.2.2
Using erubis 2.7.0
Using actionview 4.1.12
Using rack 1.5.5
Using rack-test 0.6.3
Using actionpack 4.1.12
Using mime-types 2.6.1
Using mail 2.6.3
Using actionmailer 4.1.12
Using activemodel 4.1.12
Using arel 5.0.1.20140414130214
Using activerecord 4.1.12
Using addressable 2.3.8
Using multi_json 1.11.0
Using airbrake 4.1.0
Using ansi 1.5.0
Using ast 2.1.0
Using attachable 0.0.5
Using extlib 0.9.16
Using autoparse 0.3.3
Using bcrypt 3.1.10
Using thor 0.19.1
Using railties 4.1.12
Using bootstrap-datepicker-rails 1.4.0
Using bundler 1.10.6
Using bundler-audit 0.3.1
Using cancancan 1.10.1
Using clockwork 1.2.0
Using coffee-script-source 1.9.1.1
Using execjs 2.2.2
Using coffee-script 2.4.1
Using coffee-rails 4.1.0
Using multipart-post 2.0.0
Using faraday 0.9.1
Using jwt 1.4.1
Using little-plugger 1.1.3
Using logging 2.0.0
Using memoist 0.12.0
Using signet 0.6.0
Using googleauth 0.4.1
Using launchy 2.4.3
Using retriable 1.4.1
Using google-api-client 0.8.6
Using icalendar 2.3.0
Using hike 1.2.3
Using tilt 1.4.1
Using sprockets 2.11.3
Using sprockets-rails 2.3.2
Using rails 4.1.12
Using concerto_calendar 0.0.8
Using concerto_docsplit 0.7.5
Using concerto_frontend 0.2.0
Using concerto_hardware 0.6
Using concerto_iframe 0.0.9
Using htmlentities 4.3.4
Using iso8601 0.8.6
Using ruby-ll 2.1.2
Using oga 1.2.3
Using open_uri_redirections 0.2.1
Using video_info 2.5.0
Using concerto_remote_video 0.7
Using encryptor 1.3.0
Using ruby-xslt 0.9.9
Using concerto_simple_rss 0.9
Using concerto_weather 0.1.0
Using connection_pool 1.2.0
Using delayed_job 4.0.6
Using delayed_job_active_record 4.0.3
Using orm_adapter 0.5.0
Using responders 1.1.2
Using warden 1.2.3
Using devise 3.4.1
Using docile 1.1.5
Using sass 3.4.13
Using font-awesome-sass 4.4.0
Using rubinius-core-api 0.0.1
Using rubinius-actor 0.0.2
Using girl_friday 0.11.2
Using google-analytics-turbolinks 0.0.4
Using i18n-js 3.0.0.rc9
Using jquery-rails 3.1.3
Using jquery-timepicker-rails 1.4.3
Using kaminari 0.16.3
Using libv8 3.16.14.7
Using mysql2 0.3.18
Using nprogress-rails 0.1.6.6
Using sawyer 0.6.0
Using octokit 3.8.0
Using public_activity 1.4.2
Using redcarpet 3.3.2
Using ref 1.0.5
Using rmagick 2.15.0
Using rubyzip 1.1.7
Using sass-rails 5.0.3
Using simplecov-html 0.10.0
Using simplecov 0.10.0
Using sqlite3 1.3.10
Using therubyracer 0.12.2
Using turbolinks 2.5.3
Using twitter-bootstrap-rails-confirm 1.0.4
Using uglifier 2.7.2
Bundle complete! 45 Gemfile dependencies, 108 gems now installed.
Gems in the groups postgres and development were not installed.
Bundled gems are installed into ./vendor/bundle.
I, [2015-11-14T12:17:59.431946 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/concertocons-65c9b168ddd9b3510ed092025e9230ff.eot
I, [2015-11-14T12:17:59.433166 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/concertocons-696814adbe1ea275751a1ec819242e36.svg
I, [2015-11-14T12:17:59.434193 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/concertocons-1dc6b6082f68b733e0813f01117f55da.ttf
I, [2015-11-14T12:17:59.435134 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/concertocons-ae39f1094debedb92f9d200ca661fab0.woff
I, [2015-11-14T12:17:59.436033 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/date-1df0205245b1f1f40a0e7ced6534644f.png
I, [2015-11-14T12:17:59.436950 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/filetype-icons-07b098db06678ff174a53d284bd44a1f.jpg
I, [2015-11-14T12:17:59.437862 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/green_button-5e31967ed5e59350c55f09bb1d049cc4.svg
I, [2015-11-14T12:17:59.438868 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/jquery-ui/ui-bg_flat_0_aaaaaa_40x100-a6b9620034118fd6770e4b66d028b813.png
I, [2015-11-14T12:17:59.439935 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/jquery-ui/ui-bg_flat_55_fbec88_40x100-771d84138bb66e62c4a2b8978d930e5c.pn      g
I, [2015-11-14T12:17:59.440877 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/jquery-ui/ui-bg_glass_75_d0e5f5_1x400-515b5d22f73b00de91b9d13635d82862.pn      g
I, [2015-11-14T12:17:59.441862 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/jquery-ui/ui-bg_glass_85_dfeffc_1x400-a5990f1fdc21e845582a71bc886606bd.pn      g
I, [2015-11-14T12:17:59.442849 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/jquery-ui/ui-bg_glass_95_fef1ec_1x400-0d592acba3b5111b20600cbd8d3893ce.pn      g
I, [2015-11-14T12:17:59.443850 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/jquery-ui/ui-bg_gloss-wave_55_5c9ccc_500x100-903a3afaa18ca85d51efe950549e      c23b.png
I, [2015-11-14T12:17:59.444776 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/jquery-ui/ui-bg_inset-hard_100_f5f8f9_1x100-657d52adf24434581ea6f4121542d      89f.png
I, [2015-11-14T12:17:59.445760 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/jquery-ui/ui-bg_inset-hard_100_fcfdfd_1x100-33bc90b54f79b0dd4a53ab3c80974      80a.png
I, [2015-11-14T12:17:59.446789 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/jquery-ui/ui-icons_217bc0_256x240-c076fddd95c019619d533b21ff671fb3.png
I, [2015-11-14T12:17:59.447755 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/jquery-ui/ui-icons_2e83ff_256x240-ea2e0d3cd21166f8418cf74c524d65e9.png
I, [2015-11-14T12:17:59.448751 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/jquery-ui/ui-icons_469bdd_256x240-aba9550a6a61c3cb2b07ff082b0adebd.png
I, [2015-11-14T12:17:59.449742 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/jquery-ui/ui-icons_6da8d5_256x240-e28730696ea6d38d4e46cca3308d20e3.png
I, [2015-11-14T12:17:59.450758 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/jquery-ui/ui-icons_cd0a0a_256x240-76528dbd10d2a04ebefe1aae5c545d2f.png
I, [2015-11-14T12:17:59.451788 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/jquery-ui/ui-icons_d8e7f3_256x240-ca3570587f63a28e653ea600205eef0b.png
I, [2015-11-14T12:17:59.452840 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/jquery-ui/ui-icons_f9bd01_256x240-1c47f22b30d1f31c4dcb86aa6a6e14dc.png
I, [2015-11-14T12:17:59.453733 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/logomark-375761fea80d121e4d883768fdf91154.png
I, [2015-11-14T12:17:59.454662 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/logomark@2x-f1c342e1933087601e65dfb287a99dc1.png
I, [2015-11-14T12:17:59.455610 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/next-b6fe0998e4ca1847146343c6a5848234.gif
I, [2015-11-14T12:17:59.456498 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/prev-303852f9b7e9b7eb71e57faeb3ba1543.gif
I, [2015-11-14T12:17:59.457475 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/red_button-8dbc42cea0761f5215db1a9f57d02206.svg
I, [2015-11-14T12:17:59.458419 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/slider-d0a719f2ae76fc1b34621076a2d8e3fd.png
I, [2015-11-14T12:17:59.459357 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/elements/time-778a9dcbfa911ee3770cb8bd5ac8da2a.png
I, [2015-11-14T12:17:59.460364 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/LG_baseline-38fdfd1320d0d8aeb604ad57404afee0.png
I, [2015-11-14T12:17:59.461307 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/LG_bluebg-a04d80ece19f2e05613ee2e9a5ecedba.png
I, [2015-11-14T12:17:59.462278 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/MS/iconlist_inactive-4424ebbadf43e97d8b87ec5e36893b2e.png
I, [2015-11-14T12:17:59.463175 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/MS/inner-c0b0a62200ffecd7f2f26baf4e42a805.png
I, [2015-11-14T12:17:59.464082 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/MS/outer-ecf98cfe3f1e03e1ff6fb1814fc64688.png
I, [2015-11-14T12:17:59.465069 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/button_date_states-cd1d838a1fdc388de35760d205bc1db4.png
I, [2015-11-14T12:17:59.466036 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/button_disclosure-55a1e7d03c9f77dcf2ea7b71c823c873.png
I, [2015-11-14T12:17:59.466996 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/button_feed_states-55587caab3bcb836d5137b2fb6ba8f8e.png
I, [2015-11-14T12:17:59.467971 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/button_norm_states-ad003608e0151609c7128d0f1418e4fe.png
I, [2015-11-14T12:17:59.468950 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/button_time_states-b096730704093ca2e9f83b57a9e7d39c.png
I, [2015-11-14T12:17:59.469871 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/forms/textfield_bg-8182eca1f8bb067b3a990c0730930bc6.png
I, [2015-11-14T12:17:59.470895 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/pagebg-098827ab5e8438452c7d2d2f430f539d.gif
I, [2015-11-14T12:17:59.471805 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/pagebg@2x-9ae4792fb7a227d6c733bc36e1cb3ccd.gif
I, [2015-11-14T12:17:59.472723 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/sv_left_bg-dd6bf6cef01e3212c50eff1ab332108e.png
I, [2015-11-14T12:17:59.473669 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/top-menu/button_top-menu_states-97d564f16a97a2c412245b9dbe604951.png
I, [2015-11-14T12:17:59.474669 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/top-menu/top-menu_bg-389d722dc39ccdb476d4d6bfc4221664.png
I, [2015-11-14T12:17:59.475641 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/top-menu/top-menu_logobutton-c212debb0641df43e23d4924522f4a51.png
I, [2015-11-14T12:17:59.476678 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/top-menu/top-menu_secline-d985b8dd39917aaa640617711df337ae.png
I, [2015-11-14T12:17:59.477591 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/vert-tabs_arrowbg-ad21c39ee20aa7769a1d0c1c18c9593e.png
I, [2015-11-14T12:17:59.478597 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/vert-tabs_arrowbg@2x-3fa3bc61cdd6c843ed87f28dd53d7c10.png
I, [2015-11-14T12:17:59.479534 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/viewblock/bg_lg-001ebe3e60ba9243d69d3c9fa222b5bd.png
I, [2015-11-14T12:17:59.480471 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/viewblock/bg_sm-26754065d1109b37df9467aa0dd1903b.png
I, [2015-11-14T12:17:59.481436 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/viewblock/header_bg-90c1c0250adbd151e53bfb2cabfb0978.png
I, [2015-11-14T12:17:59.482379 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/viewblock/sidebar_light-5279a3b53140265a23c8ef3b1aec991f.png
I, [2015-11-14T12:17:59.483311 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/layout/viewblock/submit_bar_bg-7f56812d702e2cb65e27b2a662d27bf6.png
I, [2015-11-14T12:17:59.484242 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/miniscreen/404_screen-1541577444e71423f08868ae87e1ef71.png
I, [2015-11-14T12:17:59.485208 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/miniscreen/500_screen-13e0f6aa983751c30c89db1fa4e0945d.png
I, [2015-11-14T12:17:59.486179 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/miniscreen/bevel_bg-d7640d71ec86a27d5350daf84b6d5994.png
I, [2015-11-14T12:17:59.487071 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/miniscreen/bevel_logo-ab5c5fbf0adfb468855aac55fbaef8d5.png
I, [2015-11-14T12:17:59.487962 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/ph/7001-7c3b944b81e3dc611cada1933fd7ea17.jpg
I, [2015-11-14T12:17:59.489802 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/ph/grid_ph-0402db0e9a769c0aed75a09461beec78.jpg
I, [2015-11-14T12:17:59.490727 #42069]  INFO -- : Writing /usr/share/concerto/public/assets/ph/ph-7d2d9c6c584c816f519ffb3f5b53c376.png
rake aborted!
Sprockets::FileNotFound: couldn't find file 'recurring_select'
  (in /usr/share/concerto/app/assets/javascripts/concerto_content_scheduling/application.js:13)
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/context.rb:106:in `resolve'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/context.rb:146:in `require_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/directive_processor.rb:217:in `process_require_directive'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/directive_processor.rb:167:in `block in process_directives'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/directive_processor.rb:165:in `each'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/directive_processor.rb:165:in `process_directives'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/directive_processor.rb:99:in `evaluate'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/context.rb:197:in `block in evaluate'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/context.rb:194:in `each'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/context.rb:194:in `evaluate'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/processed_asset.rb:12:in `initialize'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/base.rb:374:in `new'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/base.rb:374:in `block in build_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/base.rb:395:in `circular_call_protection'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/base.rb:373:in `build_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/index.rb:94:in `block in build_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/caching.rb:58:in `cache_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/index.rb:93:in `build_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/base.rb:287:in `find_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/index.rb:61:in `find_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/processed_asset.rb:111:in `block in resolve_dependencies'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/processed_asset.rb:105:in `each'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/processed_asset.rb:105:in `resolve_dependencies'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/processed_asset.rb:97:in `build_required_assets'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/processed_asset.rb:16:in `initialize'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/base.rb:374:in `new'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/base.rb:374:in `block in build_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/base.rb:395:in `circular_call_protection'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/base.rb:373:in `build_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/index.rb:94:in `block in build_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/caching.rb:58:in `cache_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/index.rb:93:in `build_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/base.rb:287:in `find_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/index.rb:61:in `find_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/bundled_asset.rb:16:in `initialize'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/base.rb:377:in `new'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/base.rb:377:in `build_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/index.rb:94:in `block in build_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/caching.rb:58:in `cache_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/index.rb:93:in `build_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/base.rb:287:in `find_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/index.rb:61:in `find_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:211:in `block in find_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:257:in `benchmark'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:210:in `find_asset'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:119:in `block in compile'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:118:in `each'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:118:in `compile'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-rails-2.3.2/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.3/lib/rake/sprocketstask.rb:146:in `with_logger'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-rails-2.3.2/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
dpkg: error processing package concerto-full (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 concerto-full
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by augustf** [comment]
I would probably remove all non-core plugins from Gemfile-plugins, get the upgrade to run successfully, and then try installing the template scheduling plugin. You may want to run an asset precompile once you've installed it.

**Comment by robp2175** [comment]
Could you be as specific as possible? Not very strong in ruby. Should I run gem uninstall?  And how do I run and asset precompile. Thanks again.

Sent from Outlook<http://aka.ms/Ox5hz3>




On Sat, Nov 14, 2015 at 12:12 PM -0800, "August" <notifications@github.com<mailto:notifications@github.com>> wrote:


I would probably remove all non-core plugins from Gemfile-plugins, get the upgrade to run successfully, and then try installing the template scheduling plugin. You may want to run an asset precompile once you've installed it.

-
